Detect the different types of OTAs at boot image extracting. The functions to extract themselves are not yet implemented.

diff --git a/reinstall-magisk-on-lineageos b/reinstall-magisk-on-lineageos
--- a/reinstall-magisk-on-lineageos
+++ b/reinstall-magisk-on-lineageos
@@ -28,6 +28,35 @@ download_latest_lineageos_build() {
 }
 
 extract_boot_image() {
+    # See https://wiki.lineageos.org/extracting_blobs_from_zips to understand the different ways to extract the boot.img file.
+    if is_ota_block_based; then
+        extract_boot_image_from_block_based_ota
+    elif is_ota_payload_based; then
+        extract_boot_image_from_payload_based_ota
+    else
+        extract_boot_image_from_file_based_ota
+    fi
+}
+
+extract_boot_image_from_file_based_ota() {
+    echo 'ERROR: the function "extract_boot_image_from_file_based_ota" is not implemented'
+    exit 1
+}
+
+extract_boot_image_from_payload_based_ota() {
+    echo 'ERROR: the function "extract_boot_image_from_payload_based_ota" is not implemented'
+    exit 1
+}
+
+is_ota_payload_based() {
+    unzip -l /tmp/lineageos-last-build.zip | grep -wq payload.bin
+}
+
+is_ota_block_based() {
+    unzip -l /tmp/lineageos-last-build.zip | grep -wq boot.img
+}
+
+extract_boot_image_from_block_based_ota() {
     unzip -od /tmp /tmp/lineageos-last-build.zip boot.img
 }
 
